spring:
  application:
    name: ribbon-consumer

server.port: 9001

#provider-service:
#  ribbon:
#    listOfServers: localhost:8081,localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
