spring:
  application:
    name: provider-service

server:
  port: 8081

eureka:
  client:
    #客户端每隔30秒从 Eureka 服务上更新一次服务信息
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:1111/eureka/

  instance:
    #每隔2s向服务端发送一次心跳，证明自已依然活着，默认30s
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我10s之内没有给你发心跳，就代表我故障了，将我剔除掉，默认90s
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 10
