server.port: 7001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        native:
#          search-locations: ./config-repo
        git:
          uri: https://gitee.com/tinjq/config-repo
          search-paths: ./
          # 公开仓库不需要填写用户名密码，私有仓库需要
#          username: username
#          password: password
#  profiles:
#    active: native
  security:
    user:
      name: tinjq-name
      password: 123123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
