spring:
  application:
    name: ribbon-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true

server.port: 9001

#provider-service:
#  ribbon:
#    listOfServers: localhost:8081,localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

#ribbon:
#  ReadTimeout: 1000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2

